# Generated by Django 5.2 on 2026-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='male', max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('student_bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('student_registration', models.DateTimeField()),
                ('percentage', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
